Thotv/create entities
longlt201203/zoomanagement pull request #4
Opened 2023-09-25 03:28 UTC by vantho2906

Create entities for account, order, ticket

2023-09-26 01:36 UTC, longlt201203 requested changes

2023-09-26 01:36 UTC, longlt201203 commented on src/main/java/com/nhom3/zoomanagement/accounts/Account.java
> +    public void ahihi(){
Ahihi đồ ngok :))

2023-09-26 01:36 UTC, longlt201203 commented on src/main/java/com/nhom3/zoomanagement/orders/IMyOrderRepository.java
Hong cần có chữ 'I' đằng trước đâu. MyOrderRepository là được rồi.
`IMyOrderRepository` => `MyOrderRepository`

2023-09-26 01:36 UTC, longlt201203 commented on src/main/java/com/nhom3/zoomanagement/orders/MyOrder.java
Check thử coi khi insert record vào thì cái `createdAt` có thực sự hoạt động chưa

2023-09-26 01:37 UTC, longlt201203 commented
À với lại tạo luôn Repository và DTO cho mỗi thằng Entity luôn Thọ ơi !!!

2023-09-26 15:39 UTC, ListKelvin commented on src/main/resources/application.properties
> +#spring.jpa.hibernate.ddl-auto = create-drop
dòng này cần hong dị :<<

2023-09-27 01:10 UTC, longlt201203 requested changes
Thêm repository

2023-09-27 01:17 UTC, longlt201203 approved these changes

2023-09-27 01:21 UTC, longlt201203 commented on src/main/resources/application.properties
> +#spring.jpa.hibernate.ddl-auto = create-drop
cần nhe

2023-09-27 01:22 UTC, merged